version: '2'
services: 
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=inkster
      - MONGO_INITDB_ROOT_PASSWORD=inkster
      - MONGO_INITDB_ROOT_DATABASE=inkster
  inkster:
    image: rainbowsprinkles/inkster:latest
    links:
      - db
    depends_on:
      - db
    environment:
      - INKSTER_DB_URI=mongodb://inkster:inkster@db/admin
      - INKSTER_DB_NAME=inkster
      - INKSTER_PORT=8000
      - INKSTER_STATIC=static
      - INKSTER_SERVE_STATIC=0
    volumes:
      - ./static:/go/src/app/static
  nginx:
    image: nginx:alpine
    ports: 
      - "8000:80"
    volumes:
      - ./server.conf:/etc/nginx/conf.d/server.conf
      - ./dist/:/etc/nginx/html/dist/
      - ./static/:/etc/nginx/html/static/
    command: /bin/sh -c "cat /etc/nginx/conf.d/server.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

